name: 🛰 API Issue
description: API 동작 이상 또는 개선 요청
title: "[api] "
labels: ["api"]
assignees: []

body:
  - type: textarea
    id: problem
    attributes:
      label: 🚨 API 문제 설명
      description: 문제가 되는 API와 그 동작을 구체적으로 설명해주세요.
      placeholder: 예) `GET /users/me` 요청 시 500 에러 발생
    validations:
      required: true

  - type: textarea
    id: request
    attributes:
      label: 📡 요청한 API 정보
      description: 요청한 URL, 메서드, 쿼리 등 정보를 포함해주세요.
      placeholder: |
        예)
        - URL: /users/me
        - Method: GET
        - Headers: Authorization: Bearer ...
    validations:
      required: true

  - type: textarea
    id: response
    attributes:
      label: 🧾 응답 내용 (선택)
      description: 에러 메시지, 응답 코드, 본문 등 가능한 정보를 첨부해주세요.
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: 🧪 실행 환경
      description: Postman, 브라우저, Node 버전 등 테스트 환경을 입력해주세요.
      placeholder: 예) Postman v10.2 / Node.js 20.11.0
    validations:
      required: true
