name: ✨ Feature Request
description: 새로운 기능 또는 개선사항 제안
title: "[FEAT] "
labels: ["enhancement"]
assignees: []

body:
  - type: textarea
    id: background
    attributes:
      label: 💡 제안 배경
      description: 이 기능이 왜 필요한지 설명해주세요.
      placeholder: 예) 유저가 X 동작을 할 때 불편함이 있어 기능 개선이 필요합니다.
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: 🎯 기대 효과
      description: 이 기능이 어떤 문제를 해결하거나 어떤 개선을 줄 수 있을지 설명해주세요.
      placeholder: 예) UX 향상, 유지보수 편의성 증대 등
    validations:
      required: true

  - type: textarea
    id: direction
    attributes:
      label: 📋 구현 방향 (선택)
      description: 생각하고 있는 대략적인 구현 방식이 있다면 간단히 적어주세요.
      placeholder: 예) 버튼 컴포넌트에 props 추가, API 수정 등
    validations:
      required: false
